const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT 
global.appUrl=process.env.APP_URL || ""     // put your deploy app/bot url here, for 24/7 for (render , koyeb, glitch)
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || "mongodb+srv://mohsin:mohsin@cluster0.iauaztt.mongodb.net/?retryWrites=true&w=majority"
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || "mongodb+srv://mohsin:mohsin@cluster0.iauaztt.mongodb.net/?retryWrites=true&w=majority"

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/GlobalTechInfo/SUHAIL-XMD";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029VagJIAr3bbVBCpEkAM07";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029VagJIAr3bbVBCpEkAM07" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://i.ibb.co/TgwRyHR/Ephoto360-com-166de101e03cd7.jpg" || "https://i.ibb.co/TqtqWTB/Ephoto360-com-166de104a10faf.jpg" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "© GlobalTechInfo" 


global.devs = "" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923xxx Your Number";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || Math.floor(Math.random()*3)  === 1 ?  "true" : "false" ;  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "https://telegra.ph/file/82336d4b04ac81b77e18e.jpg" // "image" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923444844060,923xxxxxxxx";

global.api_smd = "https://api.junn4.my.id" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID  || "SUHAIL_13_27_09_16_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTYsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMjAxLFxuICAgICAgICAxMjksXG4gICAgICAgIDgyLFxuICAgICAgICA1MixcbiAgICAgICAgMjE0LFxuICAgICAgICAyNCxcbiAgICAgICAgMTU0LFxuICAgICAgICAzLFxuICAgICAgICAyMzgsXG4gICAgICAgIDE5NSxcbiAgICAgICAgMjUsXG4gICAgICAgIDU2LFxuICAgICAgICA5MyxcbiAgICAgICAgODQsXG4gICAgICAgIDUsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMTQ3LFxuICAgICAgICAxODgsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMTUyLFxuICAgICAgICAyMTAsXG4gICAgICAgIDIsXG4gICAgICAgIDEzNixcbiAgICAgICAgMjMzLFxuICAgICAgICAxNDgsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMTUsXG4gICAgICAgIDg3LFxuICAgICAgICAyNDcsXG4gICAgICAgIDg0XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI1MyxcbiAgICAgICAgMjQ3LFxuICAgICAgICAxNDgsXG4gICAgICAgIDQ5LFxuICAgICAgICAxNjIsXG4gICAgICAgIDg0LFxuICAgICAgICAyMDQsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMTA1LFxuICAgICAgICA5NSxcbiAgICAgICAgNDAsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMjA4LFxuICAgICAgICA0OSxcbiAgICAgICAgMTkxLFxuICAgICAgICAxMTcsXG4gICAgICAgIDE0MixcbiAgICAgICAgMTYzLFxuICAgICAgICAxODYsXG4gICAgICAgIDQ1LFxuICAgICAgICAzNSxcbiAgICAgICAgMjksXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTU5LFxuICAgICAgICAxNDMsXG4gICAgICAgIDU4LFxuICAgICAgICA3LFxuICAgICAgICA1NyxcbiAgICAgICAgNjUsXG4gICAgICAgIDU4LFxuICAgICAgICAxMDcsXG4gICAgICAgIDI3XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxOTIsXG4gICAgICAgIDM1LFxuICAgICAgICAyMzksXG4gICAgICAgIDE1NSxcbiAgICAgICAgMjI0LFxuICAgICAgICAxMjEsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMjI5LFxuICAgICAgICAxNDYsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTA5LFxuICAgICAgICAxOTksXG4gICAgICAgIDIwNCxcbiAgICAgICAgMTY5LFxuICAgICAgICAyMTgsXG4gICAgICAgIDUzLFxuICAgICAgICA4OCxcbiAgICAgICAgMTM1LFxuICAgICAgICAyMjksXG4gICAgICAgIDE4NixcbiAgICAgICAgMjAsXG4gICAgICAgIDk1LFxuICAgICAgICAzLFxuICAgICAgICAzNSxcbiAgICAgICAgMjE5LFxuICAgICAgICAxMTksXG4gICAgICAgIDU2LFxuICAgICAgICA5MSxcbiAgICAgICAgODIsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMjUwLFxuICAgICAgICAxMjFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNjgsXG4gICAgICAgIDE0MyxcbiAgICAgICAgNDcsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMjE5LFxuICAgICAgICA0NSxcbiAgICAgICAgMzcsXG4gICAgICAgIDgwLFxuICAgICAgICAyMyxcbiAgICAgICAgMTQ3LFxuICAgICAgICAxNzAsXG4gICAgICAgIDQ3LFxuICAgICAgICA2NCxcbiAgICAgICAgMTQ3LFxuICAgICAgICAxMjksXG4gICAgICAgIDczLFxuICAgICAgICAyMTUsXG4gICAgICAgIDQwLFxuICAgICAgICAyMjAsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjE2LFxuICAgICAgICAxNDksXG4gICAgICAgIDEyNSxcbiAgICAgICAgNzQsXG4gICAgICAgIDM1LFxuICAgICAgICAxNzUsXG4gICAgICAgIDIyLFxuICAgICAgICAxMTcsXG4gICAgICAgIDgsXG4gICAgICAgIDU1LFxuICAgICAgICAxMjEsXG4gICAgICAgIDExMFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMCxcbiAgICAgICAgMTg5LFxuICAgICAgICAxMzksXG4gICAgICAgIDk5LFxuICAgICAgICAyMzMsXG4gICAgICAgIDkyLFxuICAgICAgICA3NCxcbiAgICAgICAgODEsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTYxLFxuICAgICAgICA1OSxcbiAgICAgICAgMTY3LFxuICAgICAgICAzOCxcbiAgICAgICAgODQsXG4gICAgICAgIDIxMSxcbiAgICAgICAgNzQsXG4gICAgICAgIDMsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMjEyLFxuICAgICAgICAyNDYsXG4gICAgICAgIDEwMSxcbiAgICAgICAgNTEsXG4gICAgICAgIDIzOSxcbiAgICAgICAgODEsXG4gICAgICAgIDI0MSxcbiAgICAgICAgOTAsXG4gICAgICAgIDU4LFxuICAgICAgICAxMixcbiAgICAgICAgNjksXG4gICAgICAgIDIzNixcbiAgICAgICAgMjM3LFxuICAgICAgICA3N1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMTksXG4gICAgICAgIDEwNCxcbiAgICAgICAgMjQ2LFxuICAgICAgICAxOTAsXG4gICAgICAgIDEyNixcbiAgICAgICAgNjgsXG4gICAgICAgIDczLFxuICAgICAgICAzNSxcbiAgICAgICAgODcsXG4gICAgICAgIDExOCxcbiAgICAgICAgOTQsXG4gICAgICAgIDkxLFxuICAgICAgICA4LFxuICAgICAgICAxOTcsXG4gICAgICAgIDEyMCxcbiAgICAgICAgNTIsXG4gICAgICAgIDEzMSxcbiAgICAgICAgNzQsXG4gICAgICAgIDQ0LFxuICAgICAgICAyMDUsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMTA2LFxuICAgICAgICAyMTgsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMzUsXG4gICAgICAgIDExMyxcbiAgICAgICAgMTMxLFxuICAgICAgICAxOTYsXG4gICAgICAgIDg1LFxuICAgICAgICAzNixcbiAgICAgICAgMTUsXG4gICAgICAgIDZcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDIzNCxcbiAgICAgICAgICA0MyxcbiAgICAgICAgICA5MixcbiAgICAgICAgICAyNDcsXG4gICAgICAgICAgOTUsXG4gICAgICAgICAgMTI2LFxuICAgICAgICAgIDk2LFxuICAgICAgICAgIDEwLFxuICAgICAgICAgIDIxMCxcbiAgICAgICAgICAzMixcbiAgICAgICAgICAyLFxuICAgICAgICAgIDExMSxcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDY5LFxuICAgICAgICAgIDYzLFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICA1OSxcbiAgICAgICAgICAxNixcbiAgICAgICAgICAxNDEsXG4gICAgICAgICAgMjQ3LFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAxNzAsXG4gICAgICAgICAgMTMxLFxuICAgICAgICAgIDQ4LFxuICAgICAgICAgIDExMSxcbiAgICAgICAgICAxMjIsXG4gICAgICAgICAgOTUsXG4gICAgICAgICAgMTM3LFxuICAgICAgICAgIDE0NCxcbiAgICAgICAgICAxMjVcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTIyLFxuICAgICAgICAgIDIwMCxcbiAgICAgICAgICAxNDksXG4gICAgICAgICAgMTE0LFxuICAgICAgICAgIDIyNSxcbiAgICAgICAgICAxNTcsXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDE1MixcbiAgICAgICAgICAxLFxuICAgICAgICAgIDg5LFxuICAgICAgICAgIDUyLFxuICAgICAgICAgIDEzMyxcbiAgICAgICAgICAyNTQsXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDIyMSxcbiAgICAgICAgICA3LFxuICAgICAgICAgIDE1NSxcbiAgICAgICAgICAyMTAsXG4gICAgICAgICAgMjQ5LFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDU4LFxuICAgICAgICAgIDU5LFxuICAgICAgICAgIDQ1LFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgOTcsXG4gICAgICAgICAgMjU1LFxuICAgICAgICAgIDE2LFxuICAgICAgICAgIDEyLFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICA2NFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTU1LFxuICAgICAgICAxMzksXG4gICAgICAgIDUzLFxuICAgICAgICAxMjksXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjA1LFxuICAgICAgICA4MixcbiAgICAgICAgMTQsXG4gICAgICAgIDI0MyxcbiAgICAgICAgNDEsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMTU5LFxuICAgICAgICAxODAsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMTQsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTA5LFxuICAgICAgICA0OCxcbiAgICAgICAgMTQ4LFxuICAgICAgICAxNjUsXG4gICAgICAgIDE1NixcbiAgICAgICAgNzIsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTY4LFxuICAgICAgICAxNSxcbiAgICAgICAgNTEsXG4gICAgICAgIDE0LFxuICAgICAgICAxODAsXG4gICAgICAgIDg2LFxuICAgICAgICA1MSxcbiAgICAgICAgMTIxLFxuICAgICAgICA4LFxuICAgICAgICAyMTUsXG4gICAgICAgIDI0NCxcbiAgICAgICAgNzUsXG4gICAgICAgIDUwLFxuICAgICAgICAxNTQsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMTksXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTU3LFxuICAgICAgICAzNSxcbiAgICAgICAgMjQ2LFxuICAgICAgICAyMixcbiAgICAgICAgMjAyLFxuICAgICAgICAxNjEsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTAyLFxuICAgICAgICAxNTMsXG4gICAgICAgIDIxNixcbiAgICAgICAgMjQ4LFxuICAgICAgICAxMSxcbiAgICAgICAgMTM1LFxuICAgICAgICAxNTMsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMzQsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTA1LFxuICAgICAgICA5NCxcbiAgICAgICAgNjMsXG4gICAgICAgIDUzLFxuICAgICAgICAyNTQsXG4gICAgICAgIDEzNVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMTM0LFxuICBcImFkdlNlY3JldEtleVwiOiBcIlpzTGZ6MU9rN0FWQU56QlJrNlVqUytyZzNZZ1U1WHZQOEkzNURMTVBlOTg9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMCxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcInk2T1hqZW56U29DNVc2ZzM1SVVFMFFcIixcbiAgXCJwaG9uZUlkXCI6IFwiY2E3Zjk1YzQtMDg3Ny00YmRhLWJkZDEtMDYxZjNmYWZlM2RhXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDY2LFxuICAgICAgMTMsXG4gICAgICA0OSxcbiAgICAgIDIxMyxcbiAgICAgIDE3MCxcbiAgICAgIDUxLFxuICAgICAgMTcwLFxuICAgICAgMTUxLFxuICAgICAgMjQ0LFxuICAgICAgMTYzLFxuICAgICAgMTY2LFxuICAgICAgMTA1LFxuICAgICAgMTMxLFxuICAgICAgMTE4LFxuICAgICAgNTAsXG4gICAgICAxOTEsXG4gICAgICA0OSxcbiAgICAgIDE5NCxcbiAgICAgIDQ4LFxuICAgICAgMTlcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiBmYWxzZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE3MixcbiAgICAgIDc0LFxuICAgICAgMTkyLFxuICAgICAgMTA2LFxuICAgICAgMTA1LFxuICAgICAgMTg0LFxuICAgICAgMjYsXG4gICAgICAxMDMsXG4gICAgICAxOTMsXG4gICAgICAyMDksXG4gICAgICAyMjQsXG4gICAgICAxNCxcbiAgICAgIDI5LFxuICAgICAgMTUyLFxuICAgICAgMzksXG4gICAgICAxNTgsXG4gICAgICAxNTYsXG4gICAgICAyNDQsXG4gICAgICAxMzYsXG4gICAgICA3OFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ09tS2xmSUhFTDdrb0xjR0dBSWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiK0dUSGRGSGZjOG1yT2hKK2NxK0RjTHZmaDNqMURZY1FNRFpINE5XdUtEMD1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJudnkzWndWdzZTb3UyaVVEWlhUUGNXYlpackhJS3hFWDNrdlZFWDdqMTQ4NXZkdVpRZVoyVWUycm1ZcTZkbmhoWERycjN3NW9JS0NvQjlpUHU2MExEdz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJTM1FtdlQ2MDhpbXBtZXdEaUROOUdZS2JueTZWYVFOeGJ4dlBNUWk5RTZJaUNrS1BLd05adGxkdGlCUHlOSzJNMkdlN3hmR1B4ZHR2V0pRV0ZaaFJoQT09XCJcbiAgfSxcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjkyMzE5MjE3MzM5ODo1NEBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiMTQ0NTc3NjA4NTU2NjE5OjU0QGxpZFwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiOTIzMTkyMTczMzk4OjU0QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMjQ4LFxuICAgICAgICAgIDEwMCxcbiAgICAgICAgICAxOTksXG4gICAgICAgICAgMTE2LFxuICAgICAgICAgIDgxLFxuICAgICAgICAgIDIyMyxcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgMjAxLFxuICAgICAgICAgIDE3MSxcbiAgICAgICAgICA1OCxcbiAgICAgICAgICAxOCxcbiAgICAgICAgICAxMjYsXG4gICAgICAgICAgMTE0LFxuICAgICAgICAgIDE3NSxcbiAgICAgICAgICAxMzEsXG4gICAgICAgICAgMTEyLFxuICAgICAgICAgIDE4NyxcbiAgICAgICAgICAyMjMsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDEyMCxcbiAgICAgICAgICAyNDUsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDE2LFxuICAgICAgICAgIDQ4LFxuICAgICAgICAgIDU0LFxuICAgICAgICAgIDcxLFxuICAgICAgICAgIDIyNCxcbiAgICAgICAgICAyMTMsXG4gICAgICAgICAgMTc0LFxuICAgICAgICAgIDQwLFxuICAgICAgICAgIDYxXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjY0OTMyNTEsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFPZGpcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQU9kai5qc29uIjogIntcImtleURhdGFcIjpcIks3TXJ6c1NsN2wzZnIyMEF5ZEdSN29GdkFWNG1tODFUY0F6SXFXYVZwSmM9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjExODQ2ODk2OCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBT2RrLmpzb24iOiAie1wia2V5RGF0YVwiOlwiUDhVYjhsSUwyb0tsTUIyaENHS2JyV0gzREp3ZERRNFJiY29FMU91bThmaz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoyMTE4NDY4OTY4LFwiY3VycmVudEluZGV4XCI6NCxcImRldmljZUluZGV4ZXNcIjpbMCwxLDIsNF19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBT2RsLmpzb24iOiAie1wia2V5RGF0YVwiOlwiVUx6ei81QXFPZVlnS0I4ZVF5cFpJeUlialRzb2RpN2doZlM4K3pyYmdXVT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoyMTE4NDY4OTY4LFwiY3VycmVudEluZGV4XCI6NCxcImRldmljZUluZGV4ZXNcIjpbMCwxLDRdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQU9kbS5qc29uIjogIntcImtleURhdGFcIjpcImw5anRqZDBwMndBdEtITGpxZHpvVDJHS1pQWlMxeHhQbEhtejFxelRXUU09XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjExODQ2ODk2OCxcImN1cnJlbnRJbmRleFwiOjQsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzI2Mjk2NzA2OTg2XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBT2RvLmpzb24iOiAie1wia2V5RGF0YVwiOlwiZ1BGekJ0SWlIM3k2R2NMa0xaOEVtU3dnTjJyOE9EM0g4c2JOUndGTTAyWT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoyMTE4NDY4OTY4LFwiY3VycmVudEluZGV4XCI6NSxcImRldmljZUluZGV4ZXNcIjpbMCwxLDVdfSxcInRpbWVzdGFtcFwiOlwiMTcyNjI5NzIzNDQ1M1wifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQU9kcS5qc29uIjogIntcImtleURhdGFcIjpcIktidWtPL3A1TVRxNFY5blMyNCs0cFZsZkpCZmZQNnNEeHpTbGd5WTRRbnc9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjExODQ2ODk2OCxcImN1cnJlbnRJbmRleFwiOjUsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBT2RyLmpzb24iOiAie1wia2V5RGF0YVwiOlwiaUdzdEJHYWl6cGQzV3RsL1dDcnN6Q1RMTzYyUjZlZUluSzNCR3ZrWXZzYz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoyMTE4NDY4OTY4LFwiY3VycmVudEluZGV4XCI6NSxcImRldmljZUluZGV4ZXNcIjpbMF19LFwidGltZXN0YW1wXCI6XCIxNzI2NDg5NzkwODYyXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBT2RzLmpzb24iOiAie1wia2V5RGF0YVwiOlwibVZWNjAvQlVNWUJGcG92eHplTzFURVZVdTltMUQ3akVBSmxpT010bmJzTT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoyMTE4NDY4OTY5LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjY0OTI4NzE2NjRcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQURRQUFPZG4uanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJQcHJWQmhESmcrMUpxVHEvMFV6NHFyV2dPT25KM0h3WW13bkhlYWhCdnBNPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjIxMTg0Njg5NjgsXCJjdXJyZW50SW5kZXhcIjo1LFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsNTJdfSxcInRpbWVzdGFtcFwiOlwiMTcyNjI5Njc1NjU1OVwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BRFFBQU9kcC5qc29uIjogIntcImtleURhdGFcIjpcIk91YTFEWXdrdWdId05HWG84dzU3dkk1K1R6ZTQrM281YmhCclJuQkdXN289XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjExODQ2ODk2OCxcImN1cnJlbnRJbmRleFwiOjUsXCJkZXZpY2VJbmRleGVzXCI6WzAsMSw1Ml19LFwidGltZXN0YW1wXCI6XCIxNzI2MzM0NTkyNDQzXCJ9Igp9"  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.0.1-developement-x",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ GlobalTechInfo ® 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@GlobalTechInfo"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "Suhail-XMD",
  ownername:process.env.OWNER_NAME|| "Suhail-X",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "yepeTQaFk7r9ymusihgXYvdN",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "0cdb1aed858329b9793413672094ce0d";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
